### ISSUE TITLE
Untested code in docs

### ISSUE THREAD

**Issue by pnkfelix** [bodil/sized-vec#4]
Spawned off of https://github.com/rust-lang/rust/issues/61563

If you look at:

https://github.com/bodil/sized-vec/blob/617bb45990c4ae734ebabd37f9746c4399db9554/src/lib.rs#L1082-L1101

Under the current beta version of rust 1.36, we get an error from `cargo test` on this crate due to line 1098.

But as far as I can tell, the reason we are seeing this error now is not because of a regression in the compiler's behavior, but rather because this documentation example is dead code by default. The `cfg` flag at the front, under 1.35 and earlier, cause `rustdoc` not to include it. Right now `rustdoc` *might* include it in 1.36 ("might" because of https://github.com/rust-lang/rust/pull/61199 ), but the real point here is that this code example is not being tested by default, and that might represent a bug somewhere here overall.

Maybe the `impl` there should be guarded by just `cfg(feature = "generic-array")`?  Why is it `cfg(any(test, feature = "generic-array"))` ?

**Comment by bodil** [comment]
The `cfg` checks for `test` because I don't want to have to use the `--all-features` flag on `cargo test`, and `generic-array` is a dev-dependency as well as an optional dependency, which I'd have expected to be available when testing. You're right, though, that test seems to have been ignored up until now, and, more curiously, on current nightly `cargo test` fails as you've noted, while `cargo test --all-features` compiles and passes the test, so it would seem rustdoc doesn't include my listed dev-dependencies.

So I think I'm just going to make sure CI uses `cargo test --all-features`and remove the `test` guard from the `cfg`.
